-- AlterTable
ALTER TABLE "Product"
ADD COLUMN "imageCropX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "imageCropY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "imageZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
